# configuration for the entire service
service:
  apis:
    - "http_rest_v1"
    - "rabbitmq_v1"
  notification_types:
    - "mail"
    - "sms"
    - "push"
  allowed_languages:
    - "BG"
    - "EN"
    - "DE"
    - "ES"
    - "DA"
    - "CS"
  auth:
    master_client_id: abcdefgh
    master_client_secret: w3fmLYkxIybT23Uf4cC2CP8Y2VoPTDhwy5yO2BIh86dgEOS475ZZL7i5cd1efieG
    token_signing_key: 5kpyjfDATS2SleG4
    token_expiry_time: 300 # in seconds

# configuration for the HTTP server
http: 
  address: ":8081"

# configuration for the database
database:
  driver: "mysql"
  username: "root"
  password: "nsPass1234"
  host: "localhost:3306"
  name: "notifications_db"
  pool_size: 10

# needed only if 'mail' is included in `service.notification_types`
mail:
  from_email: "your-email@gmail.com"
  from_password: "your-password"
  host: "smtp.gmail.com"
  port: 587

# needed only if 'sms' is included in `service.notification_types`
# twilio configuration
sms:
  from_phone_number: "+11111111111"
  account_sid: "your-account-sid"
  authentication_token: "your-authentication-token"